run:
  timeout: 1m
  tests: false

linters:
  enable:
    - gofmt
    - golint
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    - goimports
    - goprintffuncname
    - misspell
    - prealloc
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
