run:
  timeout: 1m
  tests: false

linters-settings:
  govet:
    enable-all: true

linters:
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    - gofmt
    - goimports
    - goprintffuncname
    - govet
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
